- name: "line_strip1"
  type: "line_strip"
  frame_id: "map"
  position: [0.0, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0, 1.0]
  points:
  - point:
      x: -5.74814
      y: -5.68642
  - point:
      x: -16.4248
      y: -5.68229
  - point:
      x: -17.2092
      y: -5.30964
  - point:
      x: -17.6281
      y: -4.5394
  - point:
      x: -17.5668
      y: 2.43059
  - point:
      x: -17.3788
      y: 3.56033
  - point:
      x: -16.4476
      y: 3.72063
  - point:
      x: -12.8526
      y: 3.81549
  - point:
      x: -12.0274
      y: 3.41691
  - point:
      x: -11.7548
      y: 2.61825
  - point:
      x: -11.6019
      y: 1.64081
  - point:
      x: -11.0639
      y: 0.933739
  - point:
      x: -10.4343
      y: 0.433992
  - point:
      x: -9.32338
      y: 0.217223
  - point:
      x: -5.98785
      y: 0.168533
  - point:
      x: -4.9614
      y: -0.074909
  - point:
      x: -4.52738
      y: -0.797684
  - point:
      x: -4.62543
      y: -4.50662
  - point:
      x: -4.8518
      y: -5.27136
  - point:
      x: -5.74814
      y: -5.68642

- name: "line_strip2"
  type: "line_strip"
  frame_id: "map"
  position: [0.0, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0, 1.0]
  points:
  - point:
      x: -5.98785
      y: 0.168533
  - point:
      x: -2.15933
      y: 0.19692
  - point:
      x: 4.99304
      y: 0.217192
  - point:
      x: 5.75717
      y: -0.104776
  - point:
      x: 6.02348
      y: -0.944466
  - point:
      x: 6.07908
      y: -4.49442
  - point:
      x: 5.93119
      y: -5.41825
  - point:
      x: 5.00947
      y: -5.66782
  - point:
      x: -2.15441
      y: -5.59058
  - point:
      x: -5.74814
      y: -5.68642

- name: "line_strip3"
  type: "line_strip"
  frame_id: "map"
  position: [0.0, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0, 1.0]
  points:
  - point:
      x: -2.15441
      y: -5.59058
  - point:
      x: -3.26598
      y: -4.5187
  - point:
      x: -3.23369
      y: -0.872419
  - point:
      x: -2.85156
      y: -0.072819
  - point:
      x: -2.15933
      y: 0.19692

- name: "line_strip4"
  type: "line_strip"
  frame_id: "map"
  position: [0.0, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0, 1.0]
  points:
  - point:
      x: -17.5668
      y: 2.43059
  - point:
      x: -17.5659
      y: 9.76515
  - point:
      x: -17.263
      y: 10.5372
  - point:
      x: -16.4738
      y: 10.8419
  - point:
      x: -15.6875
      y: 10.4459
  - point:
      x: -15.3844
      y: 9.76623
  - point:
      x: -15.1949
      y: 8.95505
  - point:
      x: -14.5692
      y: 8.09041
  - point:
      x: -13.8487
      y: 7.58272
  - point:
      x: -12.886
      y: 7.35266
  - point:
      x: -5.74051
      y: 7.31712
  - point:
      x: -4.96166
      y: 6.99656
  - point:
      x: -4.65757
      y: 6.19909
  - point:
      x: -4.66632
      y: 2.48602
  - point:
      x: -4.61043
      y: 1.14056
  - point:
      x: -4.46712
      y: 0.649062
  - point:
      x: -4.00291
      y: 0.216082
  - point:
      x: -2.15933
      y: 0.19692

- name: "line_strip5"
  type: "line_strip"
  frame_id: "map"
  position: [0.0, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0, 1.0]
  points:
  - point:
      x: 6.07908
      y: -4.49442
  - point:
      x: 6.06342
      y: -6.14106
  - point:
      x: 6.45382
      y: -6.71132
  - point:
      x: 7.28647
      y: -6.984
  - point:
      x: 8.38542
      y: -7.01057
  - point:
      x: 12.109
      y: -7.00189
  - point:
      x: 13.4103
      y: -6.57861
  - point:
      x: 14.1928
      y: -5.95585
  - point:
      x: 14.5738
      y: -4.56779
  - point:
      x: 14.5846
      y: 2.76679
  - point:
      x: 14.5242
      y: 6.04684
  - point:
      x: 14.6302
      y: 9.78125
  - point:
      x: 14.185
      y: 11.1305
  - point:
      x: 13.4553
      y: 11.8081
  - point:
      x: 12.0832
      y: 12.2462
  - point:
      x: 4.93734
      y: 12.1609
  - point:
      x: 3.64635
      y: 11.8392
  - point:
      x: 2.97919
      y: 11.1709
  - point:
      x: 2.62549
      y: 10.0432
  - point:
      x: 2.49543
      y: 6.17448
  - point:
      x: 2.94114
      y: 4.83513
  - point:
      x: 3.62494
      y: 4.16208
  - point:
      x: 4.97358
      y: 3.73838
  - point:
      x: 12.1335
      y: 3.67532
  - point:
      x: 13.074
      y: 3.47931
  - point:
      x: 13.2746
      y: 2.7307
  - point:
      x: 13.2996
      y: -4.49511
  - point:
      x: 12.9686
      y: -5.24978
  - point:
      x: 12.1028
      y: -5.62825
  - point:
      x: 8.50031
      y: -5.6102
  - point:
      x: 5.00947
      y: -5.66782