- name: "box1"
  type: "cube"
  frame_id: "map"
  position: [3.5, 0.0, 2.5]
  orientation: [0.0, 0.0, 0.0, 1.0]

- name: "sphere1"
  type: "sphere"
  frame_id: "map"
  position: [5.5, 7.0, 4.0]
  orientation: [0.0, 0.0, 0.0, 1.0]
---
- name: "sphere2"
  type: "sphere"
  frame_id: "map"
  position: [0.0, 0.0, 1.0]
  orientation: [0.0, 0.0, 0.0, 1.0]